// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



// ...


// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4l2A2G-aTpbZqCxRChbD0MJCb3LHVBA',
    appId: '1:187481971197:web:330f9d07af8410dac36194',
    messagingSenderId: '187481971197',
    projectId: 'scavenge-2e89e',
    authDomain: 'scavenge-2e89e.firebaseapp.com',
    storageBucket: 'scavenge-2e89e.firebasestorage.app',
    measurementId: 'G-DRTH2Z8L4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKyab_y6ugdqZ39041shWGgSxE0Ankm70',
    appId: '1:187481971197:android:cee32d639d88d336c36194',
    messagingSenderId: '187481971197',
    projectId: 'scavenge-2e89e',
    storageBucket: 'scavenge-2e89e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPC5_SNQ4qVPNShU4tSxAQjlbisoPMWfg',
    appId: '1:187481971197:ios:2ff418935105a2fbc36194',
    messagingSenderId: '187481971197',
    projectId: 'scavenge-2e89e',
    storageBucket: 'scavenge-2e89e.firebasestorage.app',
    iosBundleId: 'com.example.scavenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPC5_SNQ4qVPNShU4tSxAQjlbisoPMWfg',
    appId: '1:187481971197:ios:2ff418935105a2fbc36194',
    messagingSenderId: '187481971197',
    projectId: 'scavenge-2e89e',
    storageBucket: 'scavenge-2e89e.firebasestorage.app',
    iosBundleId: 'com.example.scavenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4l2A2G-aTpbZqCxRChbD0MJCb3LHVBA',
    appId: '1:187481971197:web:eff349a2be824a3cc36194',
    messagingSenderId: '187481971197',
    projectId: 'scavenge-2e89e',
    authDomain: 'scavenge-2e89e.firebaseapp.com',
    storageBucket: 'scavenge-2e89e.firebasestorage.app',
    measurementId: 'G-9BPWZ12RRZ',
  );
}
